spring:
  boot:
    admin.client.url=http://localhost:8080
  datasource:
    driverClassName=org.h2.Driver
    url=jdbc:h2:mem:testdb
    username=sa
    password=password
  h2:
    console.enabled=true
    console.path=/h2-console
  jpa:
    database-platform=org.hibernate.dialect.H2Dialect
